version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:admin123@db:5432/go_cashfree
      - CASHFREE_CLIENT_ID=${CASHFREE_CLIENT_ID}
      - CASHFREE_CLIENT_SECRET=${CASHFREE_CLIENT_SECRET}
      - CASHFREE_ENVIRONMENT=${CASHFREE_ENVIRONMENT:-test}
      - PORT=8080
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - cashfree-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=go_cashfree
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations.sql:/docker-entrypoint-initdb.d/migrations.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - cashfree-network

  adminer:
    image: adminer:latest
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - cashfree-network

volumes:
  postgres_data:

networks:
  cashfree-network:
    driver: bridge
